#!/usr/bin/env python
# coding: utf-8

import hail as hl
hl.init()


import sys
sys.path.append('/home/siwei')

from generic import *
from constraint_basics import *



def filter_for_element(ht: Union[hl.MatrixTable, hl.Table], 
                     bed_path: str, bed_reference_genome: str) -> Union[hl.MatrixTable, hl.Table]:

    # bed = hl.import_bed(bed_path, bed_reference_genome)
    bed = hl.import_bed(bed_path, bed_reference_genome, skip_invalid_intervals=True)
    
    ht = ht.filter(hl.is_defined(bed[ht.locus]))
    # return ht.annotate(element_id = bed[ht.locus].target)
    return ht.annotate(element_id = bed.index(ht.locus,all_matches=True).target).explode('element_id')



def filter_for_mu(t: Union[hl.MatrixTable, hl.Table]) -> Union[hl.MatrixTable, hl.Table]:
    """
    Filter to non-coding annotations, remove GERP outliers
    GERP cutoffs determined by finding 5% and 95% percentiles on list generated by:
    ```
    gerp_data = ht.aggregate(gerp=hl.agg.hist(context_ht.gerp, -12.3, 6.17, 100))
    cumulative_data = np.cumsum(summary_hist.gerp.bin_freq) + summary_hist.gerp.n_smaller
    np.append(cumulative_data, [cumulative_data[-1] + summary_hist.gerp.n_larger])
    list(zip(summary_hist.gerp.bin_edges, cumulative_data / max(cumulative_data)))
    ```
    """
    # This would pull out the consequence specific to each alternate allele, but in the case of intron and intergenic,
    # the worst consequence for one substitution is also the worst for any other at the same site, so it's ok
    # t = process_consequences(t)
    # intronic = (t.vep.worst_consequence_term == "intron_variant")
    # intergenic = (hl.is_missing(t.vep.transcript_consequences) | (hl.len(t.vep.transcript_consequences) == 0)
    #               ) & (hl.is_defined(t.vep.intergenic_consequences) | (hl.len(t.vep.intergenic_consequences) > 0))
    # criteria = (intronic | intergenic) & (t.gerp > -3.9885) & (t.gerp < 2.6607)
    criteria = (
        # (t.gerp > -3.9885) & (t.gerp < 2.6607) &
                ((t.vep.most_severe_consequence == 'intron_variant') |
                 (t.vep.most_severe_consequence == 'intergenic_variant')))
    return t.filter_rows(criteria) if isinstance(t, hl.MatrixTable) else t.filter(criteria)


def filter_bad_regions(ht: Union[hl.MatrixTable, hl.Table], 
                     bed_path: str, bed_reference_genome: str) -> Union[hl.MatrixTable, hl.Table]:
    bed = hl.import_bed(bed_path, bed_reference_genome, skip_invalid_intervals=True)
    ht = ht.filter(hl.is_defined(bed[ht.locus]), keep=False)
    return ht
  


context_ht = hl.read_table('gs://gnomad-nc-constraint-v31/context_prefiltered_chrX.ht')
genome_ht = hl.read_table('gs://gnomad-nc-constraint-v31/genome_prefiltered_chrX.ht')



###
# QC to be consistent with met_ht below
print ("Filtering coverage")
coverage_ht = hl.read_table("gs://gcp-public-data--gnomad/release/3.0.1/coverage/genomes/gnomad.genomes.r3.0.1.coverage.ht")
context_ht = context_ht.filter(coverage_ht[context_ht.locus].over_10>=0.95)

print ("Filtering bad regions")
# path = "gs://gnomad-nc-constraint-v31/mutation_rate/probalematic_regions_ENCFF356LFX_repeatMasker.bed"
# path = "gs://gnomad-nc-constraint-v31/mutation_rate/blacklist_gap2.bed"
path = "gs://gnomad-nc-constraint-v31/mutation_rate/blacklist_gap2_lcr_segdup.merged.bed"
reference_genome = 'GRCh38'

context_ht = filter_bad_regions(context_ht,path,reference_genome)  

###


##########
print ("Semi joining genome_ht")
genome_ht = genome_ht.semi_join(context_ht)
##########



# filter for element

# path = 'gs://gnomad-nc-constraint-v31/random_forest/hg38.chrom.50kb.bed'
# path = 'gs://gnomad-nc-constraint-v31/random_forest/hg38.chrom.1M.bed'
# path = 'gs://gnomad-nc-constraint-v31/random_forest/hg38.chrom.200kb.bed'
# path = 'gs://gnomad-nc-constraint-v31/random_forest/hg38.chrom.50kbexl_ENCFF356LFX_repeatMasker.bed'
# path = 'gs://gnomad-nc-constraint-v31/genome_element/hg38.chrom.1kb.exl_ENCFF356LFX_repeatMasker.bed'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_2.5_collapse_by_gene.merged.sorted.uniq_interval.lft38.bed'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_2.5_collapse_by_gene.merged.sorted.Fetal_BRAIN_add.lft38.bed'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_2.5_collapse_by_gene.Fetal_BRAIN.merged.lft38.txt'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_2.5_collapse_by_gene.Brain.merged.lft38.txt'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_2.5_collapse_by_gene.Heart.merged.lft38.txt'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_2.5_collapse_by_gene.merged.tissue_count.gt10.merged.lft38.bed'

# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/GSE86189_all_interaction.po.sorted_uniq.lft38.bed'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/All-Pairs.Natural-Ratio.all_EH37.2add.lft38.bed'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_2.5_collapse_by_gene.merged.sorted.GM12878_add.lft38.bed'
# path = 'gs://gnomad-nc-constraint-v31/enh_prom_gene/RoadmapLinks_7_4.0_collapse_by_gene.merged.sorted_uniq.GM12878.lft38.bed'
# path = 'gs://gnomad-nc-constraint-v31/genome_element/hg38.chrom.1kb.chr22.bed'
# path = 'gs://gnomad-nc-constraint-v31/genome_element/hg38.chrom.250.bed'
path = 'gs://gnomad-nc-constraint-v31/genome_element/hg38.chromX.1kb.bed'
# path = "gs://gnomad-nc-constraint-v31/genome_element/wgEncodeGencodeBasicV32.TSS_1k.loeuf_canon.bed"



reference_genome = 'GRCh38'

# filter for element
print ("Annotating element id")
context_ht = filter_for_element(context_ht,path,reference_genome)
genome_ht = filter_for_element(genome_ht,path,reference_genome)    



# methyl data
print ("Annotating methyl levels")
# met_ht = hl.read_table('gs://gnomad-nc-constraint-v31/methylation/context_prepared_methyl14_weighted_logit.ht')
# met_ht = hl.read_table('gs://gnomad-nc-constraint-v31/methylation/context_prepared_methyl14_weighted_logit_x.ht')
# met_ht = hl.read_table('gs://gnomad-nc-constraint-v31/methylation/context_prepared_methyl14_weighted_logit_cov10x95_x.ht')
met_ht = hl.read_table('gs://gnomad-nc-constraint-v31/methylation/context_prepared_methyl14_weighted_logit_exl_black_gap2_lcr_segdup_cov10x95_x.ht')

# logit20-x_exl_black_gap2_lcr_segdup_cov10x95_x
annotation = {
    'methyl14_weighted_logit_level': hl.case().when(
        met_ht.methyl14_weighted_logit > 0.85, 13
    ).when(
        met_ht.methyl14_weighted_logit > 0.8, 12
    ).when(
        met_ht.methyl14_weighted_logit > 0.75, 11
    ).when(
        met_ht.methyl14_weighted_logit > 0.7, 10
    ).when(
        met_ht.methyl14_weighted_logit > 0.65, 9
    ).when(
        met_ht.methyl14_weighted_logit > 0.6, 8
    ).when(
        met_ht.methyl14_weighted_logit > 0.55, 7
    ).when(
        met_ht.methyl14_weighted_logit > 0.5, 6
    ).when(
        met_ht.methyl14_weighted_logit > 0.45, 5
    ).when(
        met_ht.methyl14_weighted_logit > 0.2, 4
    ).when(
        met_ht.methyl14_weighted_logit > 0.15, 3
    ).when(
        met_ht.methyl14_weighted_logit > 0.1, 2
    ).when(
        met_ht.methyl14_weighted_logit > 0.05, 1
    ).default(0)
    }


met_ht = met_ht.annotate(**annotation)

context_ht = context_ht.annotate(methyl_level=hl.if_else(hl.is_missing(met_ht[context_ht.key]), 0, met_ht[context_ht.key].methyl14_weighted_logit_level))
genome_ht = genome_ht.annotate(methyl_level=hl.if_else(hl.is_missing(met_ht[genome_ht.key]), 0, met_ht[genome_ht.key].methyl14_weighted_logit_level))





# select
print ("Selecting columns")
context_ht = context_ht.select('context', 'ref', 'alt', 'methyl_level','element_id','variant_type')

genome_ht = genome_ht.select('context', 'ref', 'alt', 'methyl_level', 'element_id','variant_type',
                             'freq', 'pass_filters')
# genome_ht = genome_ht.select('element_id','variant_type',
#                              'freq', 'pass_filters',) 

print ("Writing out ht")
genome_ht.write("gs://gnomad-nc-constraint-v31/genome_prefiltered_1kb_logit13-x_exl_black_gap2_lcr_segdup_cov10x95_chrX.ht", overwrite = True)
context_ht.write("gs://gnomad-nc-constraint-v31/context_prefiltered_1kb_logit13-x_exl_black_gap2_lcr_segdup_cov10x95_chrX.ht", overwrite = True)






